### PR TITLE
Added a feature to preserve or not the original code

### PR DESCRIPTION
**Pull request by aletorrado**
Hi, I added a `preserve` parameter that defaults to true, consistent with how other common postcss plugins handles this matter (more on this [here](https://github.com/search?q=repo%3Acsstools%2Fpostcss-plugins%20preserve&type=code)).

Thanks!

### CODE REVIEW

**Comment by ai** [comment]
Let's use a different name for parameter. `classOnly` or something like this, to highlight that it is another mode.

**Comment by aletorrado** [comment]
Sure. I used `onlySelectors` as not just classes may be used, but any other selector would work.

**Comment by ai** [comment]
You need to add more tests to keep 100% lines coverage.

And let’s name option as `removeMedia`.

**Comment by aletorrado** [comment]
Sure. I've just added those.

**Pull request merged**
